name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd /home/Bala/ECommerce/RestoreCourse
          git pull origin main

      - name: Run deploy script
        run: |
          chmod +x /home/Bala/deploy.sh
          /home/Bala/deploy.sh
